### ISSUE TITLE
Still repeatedly crashing with techage mod loaded.  No errors loged just a segfault and restart even when in debug mode using gdb.

### ISSUE THREAD

**Issue by joe7575** [joe7575/techage#152]
Still repeatedly crashing with techage mod loaded.  No errors loged just a segfault and restart even when in debug mode using gdb.

_Originally posted by @kizeren in https://github.com/joe7575/techage/issues/151#issuecomment-1806908415_

**Comment by joe7575** [comment]
Please try when you only disable the collider in init.lua

```
-- TA4 Collider
--dofile(MP.."/collider/vacuumtube.lua")
--dofile(MP.."/collider/magnet.lua")
--dofile(MP.."/collider/inlets.lua")
--dofile(MP.."/collider/cooler.lua")
--dofile(MP.."/collider/detector.lua")
--dofile(MP.."/collider/worker.lua")
```

**Comment by kizeren** [comment]
Steps so far.  Commented out collider and it still crashed.  Due to moving over to postgresql I didn't get backups set up fast enough before first crash happened.  Removing all of my techage seemed to fix it.  However lag from minetest.evet() shoots through the roof still.  Starting to think when the crash happened it corrupted the world.  We had to remove a few mods due to crashing after the techage problem started.

**Comment by kizeren** [comment]
As for now.  I am unable to pinpoint if it is a clash in mods or just bad luck with the world database.

**Comment by kizeren** [comment]
This can be closed.  Though I couldn't really pin down the problem.  I suspect the sata drive it was on was dieing.
