### ISSUE TITLE
Warnings spam with moreblocks 3.0

### ISSUE THREAD

**Issue by Niklp09** [joe7575/techage#86]
The warnings are displayed after the server start which means that singleplayer clients get them in the chat.
moreblocks 3.0 PR https://github.com/minetest-mods/moreblocks/pull/191

![grafik](https://user-images.githubusercontent.com/89982526/179577721-d847474b-d221-4457-bc5c-bee03d42b647.png)

[warnings.txt](https://github.com/joe7575/techage/files/9134378/warnings.txt)

**Comment by joe7575** [comment]
To get rid of the spam messages, comment out the line https://github.com/joe7575/techage/blob/master/init.lua#L313
The recipe_checker checks, if two or more items have the same recipe, which is/was the case for all moreblocks items.

To suppress all the error messages I added the check:

```lua
if not string.find(name, "slab") and not string.find(name, "stair") then
```

But obviously all the items get new names. I don't know, if it is a good idea to give the items new names...

**Comment by fluxionary** [comment]
the issue is that 2 things have the same recipe, ignoring the layout of the grid. you should at least make use of the "width" and "method" values that `get_all_craft_recipes` returns. 

ideally the API would give an easy way to check whether a recipe was shaped vs. shapeless and filter your errors accordingly, but I don't think there is w/out using craft prediction. 

also, this should probably be a warning, not an error - there's ways to programmatically manage recipes that actually conflict, though i don't know of any inventory manager that does so.

**Comment by fluxionary** [comment]
> But still the question: How do you prevent "unknown nodes" when you rename all items?

`minetest.register_alias`

**Comment by joe7575** [comment]
recipe checker is disabled by default
